language: c

compiler:
  - gcc

env:
  global:
    - CFLAGS="-Wall -Werror -ggdb3"
  matrix:
    - USE_OUR_OWN_MD5=0 BUILD_STATIC=0
    - USE_OUR_OWN_MD5=1 BUILD_STATIC=0
    - USE_OUR_OWN_MD5=0 BUILD_STATIC=1
    - USE_OUR_OWN_MD5=1 BUILD_STATIC=1
    # cross-compile using mingw
    - USE_OUR_OWN_MD5=1 BUILD_STATIC=1 CC=i686-w64-mingw32-gcc   CXX=i686-w64-mingw32-c++   CMAKE_SYSTEM_NAME=Windows ROOT=/usr/i686-w64-mingw32
    - USE_OUR_OWN_MD5=1 BUILD_STATIC=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-c++ CMAKE_SYSTEM_NAME=Windows ROOT=/usr/x86_64-w64-mingw32

script: mkdir build && cd build && cmake -DZLIB_ROOT:PATH=$ROOT -DCMAKE_SYSTEM_NAME=$CMAKE_SYSTEM_NAME -DCMAKE_INSTALL_PREFIX:PATH=/var/tmp/unshield -DUSE_OUR_OWN_MD5=$USE_OUR_OWN_MD5 -DBUILD_STATIC=$BUILD_STATIC .. && make && make install && ../run-tests.sh

before_install:
  # https://bugs.launchpad.net/ubuntu/+source/mingw-w64/+bug/1022397
  - sudo add-apt-repository ppa:mingw-packages/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-mingw-w64 g++-mingw-w64 zlib-mingw-w64-cross -y

