language: c

compiler:
  - gcc

env:
  global:
    - CFLAGS="-Wall -Werror -ggdb3"
  matrix:
    - USE_OUR_OWN_MD5=0 BUILD_STATIC=0
    - USE_OUR_OWN_MD5=1 BUILD_STATIC=0
    - USE_OUR_OWN_MD5=0 BUILD_STATIC=1
    - USE_OUR_OWN_MD5=1 BUILD_STATIC=1

# cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/var/tmp/unshield . && make && make install
script: cmake -DCMAKE_INSTALL_PREFIX:PATH=/var/tmp/unshield -DUSE_OUR_OWN_MD5=$USE_OUR_OWN_MD5 -DBUILD_STATIC=$BUILD_STATIC . && make && make install
